### ISSUE TITLE
Not working inside official Docker python image

### ISSUE THREAD

**Issue by ghost** [Ketouem/flask-boto3#7]
I'm trying to install in inside [Docker Python](https://hub.docker.com/_/python/) image, but it returns `ModuleNotFoundError: No module named 'pip.req` error. Here's the sample Dockerfile

```
FROM python:3

RUN pip install flask-boto3
```

**Comment by Ketouem** [comment]
This issue has been fixed by https://github.com/Ketouem/flask-boto3/commit/607f9e2e06c9da7af6e20027602e8615e9b6c8ce . This version has yet to be released on the cheeseshop, so at the moment you can clone the source and `pip install` it manually. I'll close this issue once a new version will be tagged and released.

**Comment by Ketouem** [comment]
Fixed with version `0.3.2` that handles `pip` 10+.  I've checked it with `docker run -it --rm python:3 pip install flask-boto3`
